# Generated by Django 4.2.20 on 2025-03-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0002_airport_aliance_remove_airline_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airline",
            name="airline_code",
            field=models.IntegerField(null=True),
        ),
    ]
