# Generated by Django 4.2.20 on 2025-03-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0004_alliance_remove_airline_aliance_delete_aliance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airline",
            name="airports",
            field=models.ManyToManyField(
                blank=True, related_name="airlines", to="airlines.airport"
            ),
        ),
    ]
