# Generated by Django 5.1.7 on 2025-03-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airport_name", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=2)),
                ("city_code", models.CharField(max_length=3)),
                ("airport_code", models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Aliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="airline",
            name="name",
        ),
        migrations.AddField(
            model_name="airline",
            name="airline_code",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="airline",
            name="airline_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="airline",
            name="founded",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airline",
            name="headquarters_city_code",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="airline",
            name="aliance",
            field=models.ManyToManyField(to="airlines.aliance"),
        ),
    ]
