# Generated by Django 4.2.20 on 2025-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0003_alter_airline_airline_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="airline",
            name="aliance",
        ),
        migrations.DeleteModel(
            name="Aliance",
        ),
        migrations.AddField(
            model_name="airline",
            name="alliance",
            field=models.ManyToManyField(
                blank=True, related_name="airline_alliance", to="airlines.alliance"
            ),
        ),
    ]
